@startuml Rental Car Booking System

class RegisteredUser {
  userId : ObjectId  
  name : String
  email : String
  password : String
  tel : String
  role : String
  createAt : Date

  +getBookings() 
  +getBooking()
  +updateBooking()
  +deleteBooking()
  +createBooking()
}

class NonRegisteredUser{
  +Register()
}

class Administrator {
  AdminId : ObjectId  
  name : String
  email : String
  password : String
  tel : String
  role : String
  createAt : Date
 
  +getBookings()
  +updateBooking()
  +deleteBooking()
}

class Booking {
  bookingId : ObjectId
  bookingDate: Date
  user: ObjectId
  car:ObjectId
  createdAt: Date
}

class car {
  carId : ObjectId
  brand:String
   type:String
   pricePerDay: Number
   licensePlate :String
   address: String
   district: String
   province: String
   postalcode:String
  googleMapsURL:String
   imageURL:String
    tel: String
}

NonRegisteredUser-- Administrator : register
NonRegisteredUser -- RegisteredUser : register
Booking "1" -- "1" car : book the car
RegisteredUser "1" -- "*" Booking : has 
Administrator -- car: can RUD

@enduml